version: '3.7'


volumes:
  esdata:
  bcdshare:
  db:
    driver: local

services:
#  builder:
#    container_name: builder
#    working_dir: /
#    build:
#      dockerfile: images/node.dev.Dockerfile
#      context: .
#    command:
#      - "sleep"
#      - "3600"
#      # - "/home/node/common/scripts/install-run-rush.js"
#      # - "build:watch"
#    volumes:
#      - './apps:/home/node/apps'
#      - './libs:/home/node/libs'


  bootstrap:
    container_name: bootstrap
    build:
      dockerfile: images/bootstrap-node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    networks:
      p2p:
        ipv4_address: 172.24.2.100

  oracle-1:
    container_name: oracle-1
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1MnmtP4uAcgMpeZN6JtyziXeFqqwQG6yn6 # Eve
      - POLLING_INTERVAL_MILLISECONDS=2000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_ID=12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1
      - P2P_PEER_PUBLIC_KEY=CAESIH+cTTTZ4gyqjEsn4L17gs9BTYU1ZeAnrBbUqQQQ9uW2
      - P2P_PEER_PRIVATE_KEY=CAESQENvWXyvlXtuw58TMrMF45ffJUza23h8zHSvssitueRgf5xNNNniDKqMSyfgvXuCz0FNhTVl4CesFtSpBBD25bY=
    networks:
      p2p:
        ipv4_address: 172.24.2.1

  oracle-2:
    container_name: oracle-2
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1R2oNqANNy2vZhnZBJc8iMEqW79t85Fv7L # Mallory
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_ID=12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2
      - P2P_PEER_PUBLIC_KEY=CAESIB3LuOsvQXa/QtLkCtHqfEdDnXDiDtGIKB42deJZQSZb
      - P2P_PEER_PRIVATE_KEY=CAESQJhgTKhCqif5bg/4RS4mPfjIp/TNA6c7licLcTFumPchHcu46y9Bdr9C0uQK0ep8R0OdcOIO0YgoHjZ14llBJls=
    networks:
      p2p:
        ipv4_address: 172.24.2.2

  oracle-3:
    container_name: oracle-3
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1VGyrip8uZDWoyssXDP7d1boGdpQcaaMXc # Oscar
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_ID=12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_PUBLIC_KEY=CAESIJwuGA2Ua44At3SqYSvFPk/S4ZK8JIChdtEIHowkTCno
      - P2P_PEER_PRIVATE_KEY=CAESQP9bMHtXPkMTF4/sitPzQuuSsR7rBsyCZIlwT8bLo0gvnC4YDZRrjgC3dKphK8U+T9LhkrwkgKF20QgejCRMKeg=
    networks:
      p2p:
        ipv4_address: 172.24.2.3

  oracle-4:
    container_name: oracle-4
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_ID=12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34
      - P2P_PEER_PUBLIC_KEY=CAESIIpE2iakPl9DwCEBQe8byn/AbxyFyp/6wswDEjAzTPV/
      - P2P_PEER_PRIVATE_KEY=CAESQFT7tBloxfCzLLLww4EZzm2l0qZiVBuEuAbD3jzLPbWZikTaJqQ+X0PAIQFB7xvKf8BvHIXKn/rCzAMSMDNM9X8=
    networks:
      p2p:
          ipv4_address: 172.24.2.4


#  signatory:
#    image: ecadlabs/signatory:v0.3.0-beta-rc2-amd64
#    ports:
#      - "6732:6732"
#    volumes:
#      - ./signatory.dev.yaml:/etc/signatory.yaml
#      - ./secret.json:/etc/secret.json


networks:
  p2p:
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
