version: '3.7'

volumes:
  esdata:
  bcdshare:
  db:
    driver: local

services:
  #  builder:
  #    container_name: builder
  #    working_dir: /
  #    build:
  #      dockerfile: images/node.dev.Dockerfile
  #      context: .
  #    command:
  #      - "sleep"
  #      - "3600"
  #      # - "/home/node/common/scripts/install-run-rush.js"
  #      # - "build:watch"
  #    volumes:
  #      - './apps:/home/node/apps'
  #      - './libs:/home/node/libs'

  bootstrap:
    container_name: bootstrap
    build:
      dockerfile: images/bootstrap-node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    networks:
      p2p:
        ipv4_address: 172.24.2.100

  oracle-1:
    container_name: oracle-1
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1MnmtP4uAcgMpeZN6JtyziXeFqqwQG6yn6 # Eve
      - POLLING_INTERVAL_MILLISECONDS=2000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1
      - P2P_PEER_PUBLIC_KEY=CAESIH+cTTTZ4gyqjEsn4L17gs9BTYU1ZeAnrBbUqQQQ9uW2
      - P2P_PEER_PRIVATE_KEY=CAESQENvWXyvlXtuw58TMrMF45ffJUza23h8zHSvssitueRgf5xNNNniDKqMSyfgvXuCz0FNhTVl4CesFtSpBBD25bY=
      - TEZOS_ADDRESS=tz1eAoFgsys8PhTUvT3V3eq2BFaZp8UsGNsr
      - TEZOS_SECRET_KEY=edskRkawwQimT7qNaw4g99dKh3ExUt3corurNLUwvYo2vwwAGdy6NK4At1QLEy9Km24TuwCFfr5k97wvDxKBn5iQqTxdvvpdjt
      - ALPHAVANTAGE_API_KEY=LOKAGZEB6UK7JJWS
      - MESSARI_API_KEY=7a4ace98-90a6-4792-81ad-5364afc6698d
    networks:
      p2p:
        ipv4_address: 172.24.2.1

  oracle-2:
    container_name: oracle-2
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1R2oNqANNy2vZhnZBJc8iMEqW79t85Fv7L # Mallory
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2
      - P2P_PEER_PUBLIC_KEY=CAESIB3LuOsvQXa/QtLkCtHqfEdDnXDiDtGIKB42deJZQSZb
      - P2P_PEER_PRIVATE_KEY=CAESQJhgTKhCqif5bg/4RS4mPfjIp/TNA6c7licLcTFumPchHcu46y9Bdr9C0uQK0ep8R0OdcOIO0YgoHjZ14llBJls=
      - TEZOS_ADDRESS=tz1MBNfBnNn8fZCJVrrXV95FSgyuUxbmt3Mm
      - TEZOS_SECRET_KEY=edskRpPWgoNUfJgZRiycPg9539KMX6Ksw5yNVDw2ukds8VEgqXLLuBDrB6dr6m7fgsAZrLMDpPkxN7kRpcNyRzwkPYhoWsBJsZ
      - TEZOS_PUBLIC_KEY=edpkunKYLbEfRLKLtn9yi9avyjQbAAbQxuPVN759ajQEDKpp4RE6GV
      - ALPHAVANTAGE_API_KEY=2XLQOTBRS8Y122VT
      - MESSARI_API_KEY=3dc85b02-55ee-4aaa-96ff-96d70a426407
    networks:
      p2p:
        ipv4_address: 172.24.2.2

  oracle-3:
    container_name: oracle-3
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1VGyrip8uZDWoyssXDP7d1boGdpQcaaMXc # Oscar
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3
      - P2P_PEER_PUBLIC_KEY=CAESIJwuGA2Ua44At3SqYSvFPk/S4ZK8JIChdtEIHowkTCno
      - P2P_PEER_PRIVATE_KEY=CAESQP9bMHtXPkMTF4/sitPzQuuSsR7rBsyCZIlwT8bLo0gvnC4YDZRrjgC3dKphK8U+T9LhkrwkgKF20QgejCRMKeg=
      - TEZOS_ADDRESS=tz1PSmvRd3ySbh5aviFEMYGD6542LL5QnrMk
      - TEZOS_SECRET_KEY=edskRzrnZoreVanzsedvSDgWV1DkNycfjMXyri9LQLVYdXTXJrxNHzdtpouGJTQ1CrQiWK6ECvHCpoYfQ2LM7j8GjJdkjqrsLE
      - TEZOS_PUBLIC_KEY=edpkuVjyKad7yCnNrCbGea7hi5Zh1zp5Cb1TvxUmnxC33fwKhq7daN
      - ALPHAVANTAGE_API_KEY=2NGJX9KAASPRJKDL
      - MESSARI_API_KEY=4d9734a2-99e7-4f54-81d9-71f5042a2e92

    networks:
      p2p:
        ipv4_address: 172.24.2.3

  oracle-4:
    container_name: oracle-4
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34
      - P2P_PEER_PUBLIC_KEY=CAESIIpE2iakPl9DwCEBQe8byn/AbxyFyp/6wswDEjAzTPV/
      - P2P_PEER_PRIVATE_KEY=CAESQFT7tBloxfCzLLLww4EZzm2l0qZiVBuEuAbD3jzLPbWZikTaJqQ+X0PAIQFB7xvKf8BvHIXKn/rCzAMSMDNM9X8=
      - TEZOS_ADDRESS=tz1KrELvNVY4xKnujkXwrVLWuzWJEg9FvA8v
      - TEZOS_SECRET_KEY=edskRjjhoUjvSZ2eGgGpvcMk6SrtpajjkzGUXDpr2EAa25VTfdtNSoD1JLhEoEnotYR6ZtRC2bCk56kwf79eqgygrMeR145ENq
      - TEZOS_PUBLIC_KEY=edpku7vkvS6XaWzFjmPDYULNyYrS7Rf1vHuoQ9FD8zVcaFNJ51bJ82
      - ALPHAVANTAGE_API_KEY=MZ42VQU1CNPC9X1U
      - MESSARI_API_KEY=bd9fcbaf-06d4-4f8d-80c3-0862ef6c53b1

    networks:
      p2p:
        ipv4_address: 172.24.2.4

  oracle-5:
    container_name: oracle-5
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5
      - P2P_PEER_PUBLIC_KEY=CAESIDlwJrvH3HgJbcpLpzROMCyxhAGuaodYse7n0tDQmtYq
      - P2P_PEER_PRIVATE_KEY=CAESQJSzbjMCYU/EeohKGea7wk+CXTbkBI7QXYJRLyXMosRTOXAmu8fceAltykunNE4wLLGEAa5qh1ix7ufS0NCa1io=
      - TEZOS_ADDRESS=tz1YKquTvvSE2B5kvGyf1AYeXD6b6cMDSzDe
      - TEZOS_SECRET_KEY=edskRts3yovQnSAaK6WbyiaZdBnLk1cSeq8UEWo24xNyo1T6gZZ9yQpQ48YmvCwjjW1FpSgJ1LPZ9T3jazmh3HXLLKHDaJZVx2
      - TEZOS_PUBLIC_KEY=edpkuqoXhgeXYZxn6yVWuy9UrWKazyahPaAbwnuZYknRefeLVVK3ar
      - ALPHAVANTAGE_API_KEY=17MO51H19VMUJAPU
      - MESSARI_API_KEY=ee29b84c-34fd-4d60-827f-35f4315ac4bd
    networks:
      p2p:
        ipv4_address: 172.24.2.5

  oracle-6:
    container_name: oracle-6
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.7/tcp/23456/p2p/12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_ID=12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736
      - P2P_PEER_PUBLIC_KEY=CAESIELnLURmP5HStRjp47jIZPuoySSCSKWSiEvE7eaD1XQh
      - P2P_PEER_PRIVATE_KEY=CAESQDLrycxtQYRWmXFn5H1Z2s+FGpxHRGcpxy8qzGBS4uyFQuctRGY/kdK1GOnjuMhk+6jJJIJIpZKIS8Tt5oPVdCE=
      - TEZOS_ADDRESS=tz1TQ4fpSFNZ6D9vrcwBz9yzM2SNjDj5YoU7
      - TEZOS_SECRET_KEY=edsk2vtJ2rVoHoA3GbgDjyT5zbeVMDXZ6R4YjDskKaapgsRtiEWpaP
      - TEZOS_PUBLIC_KEY=edpkv6xHMqShSMr4CK3Vzg7mD1hina7eBkokrMoKpuYj55BVd18rjN
      - ALPHAVANTAGE_API_KEY=9BP42KVMZ0BNFVL8
      - MESSARI_API_KEY=
    networks:
      p2p:
        ipv4_address: 172.24.2.6

  oracle-7:
    container_name: oracle-7
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm /ip4/172.24.2.1/tcp/23456/p2p/12D3KooWJQWBQvefFGj3uAzKGhpZYWYGKtj2fNQAG47aov4uj9p1 /ip4/172.24.2.2/tcp/23456/p2p/12D3KooWBpgAXhUAgjPAwEk5FJ9DRB2kFbuj8KLkPPmqKKmzrXz2 /ip4/172.24.2.3/tcp/23456/p2p/12D3KooWLL2Y1JmrAXkY7r8xbuSRtasfJLAarXmAaZPYxPnzgAJ3 /ip4/172.24.2.4/tcp/23456/p2p/12D3KooWK87KmBGJZZMP3keux62VF515mFRbNRFwbYxib7wWQR34 /ip4/172.24.2.5/tcp/23456/p2p/12D3KooWDgabT39cFp5j5mvJgiGPEppMuVgDCsNtBCh1Q8ejBCA5 /ip4/172.24.2.6/tcp/23456/p2p/12D3KooWEKXXjviRoWwoB37UzBT4qjUBbQH8bypWy3YWmyfvR736
      - P2P_PEER_ID=12D3KooWRGcN9uh633ucfUJ3XQ69n31mB2jPHKtrw7mfCSJdLz97
      - P2P_PEER_PUBLIC_KEY=CAESIOWYdQw3IH7qCQg5+LVgLEsesRldcVJdDwpy/TNSxAty
      - P2P_PEER_PRIVATE_KEY=CAESQHqJ13l1im8Zw4UM57IclZxhxqsxYwjrNXXhNQEx7UGQ5Zh1DDcgfuoJCDn4tWAsSx6xGV1xUl0PCnL9M1LEC3I=
      - TEZOS_ADDRESS=tz1bPLbmiseCCWtW7RZ9t2RkNyboB9XT4exJ
      - TEZOS_SECRET_KEY=edsk4AzUdwSFu383eMf8eve56Q2pJxy1eWt4BnzKkLKMdKurHgTeaf
      - TEZOS_PUBLIC_KEY=edpku8MxEyEKHPsPeUBSBz5a5QbemdPbiQVsobdC3SnC9UDf4yMHTL
      - ALPHAVANTAGE_API_KEY=HAD0Z5KJX7XPCXOO
      - MESSARI_API_KEY=0e630780-f69c-46e4-a796-3fee1252f358
    networks:
      p2p:
        ipv4_address: 172.24.2.7

#  signatory:
#    image: ecadlabs/signatory:v0.3.0-beta-rc2-amd64
#    ports:
#      - "6732:6732"
#    volumes:
#      - ./signatory.dev.yaml:/etc/signatory.yaml
#      - ./secret.json:/etc/secret.json

networks:
  p2p:
    ipam:
      driver: default
      config:
        - subnet: '172.24.2.0/16'
