version: '3.7'


volumes:
  esdata:
  bcdshare:
  db:
    driver: local

services:
#  builder:
#    container_name: builder
#    working_dir: /
#    build:
#      dockerfile: images/node.dev.Dockerfile
#      context: .
#    command:
#      - "sleep"
#      - "3600"
#      # - "/home/node/common/scripts/install-run-rush.js"
#      # - "build:watch"
#    volumes:
#      - './apps:/home/node/apps'
#      - './libs:/home/node/libs'


  bootstrap:
    container_name: bootstrap
    build:
      dockerfile: images/bootstrap-node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    networks:
      p2p:
        ipv4_address: 172.24.2.100

  oracle-1:
    container_name: oracle-1
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1MnmtP4uAcgMpeZN6JtyziXeFqqwQG6yn6 # Eve
      - POLLING_INTERVAL_MILLISECONDS=2000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
    networks:
      p2p:
        ipv4_address: 172.24.2.1

  oracle-2:
    container_name: oracle-2
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1R2oNqANNy2vZhnZBJc8iMEqW79t85Fv7L # Mallory
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
    networks:
      p2p:
        ipv4_address: 172.24.2.2

  oracle-3:
    container_name: oracle-3
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1VGyrip8uZDWoyssXDP7d1boGdpQcaaMXc # Oscar
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
    networks:
      p2p:
        ipv4_address: 172.24.2.3

  oracle-4:
    container_name: oracle-4
    build:
      dockerfile: images/node.dev.Dockerfile
      context: .
    volumes:
      - './apps:/home/node/apps'
      - './libs:/home/node/libs'
    environment:
      - RPC_URL=http://flextesa:20000
      - ORACLE_PKH=tz1NdjbFHLxbKEUXhXgjyLfQSCbq6oy5b7Px # Trudy
      - POLLING_INTERVAL_MILLISECONDS=1000
      - SIGNER_URL=http://signatory:6732
      - P2P_BOOTSTRAP_PEERS=/ip4/172.24.2.100/tcp/23456/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
    networks:
      p2p:
          ipv4_address: 172.24.2.4


#  signatory:
#    image: ecadlabs/signatory:v0.3.0-beta-rc2-amd64
#    ports:
#      - "6732:6732"
#    volumes:
#      - ./signatory.dev.yaml:/etc/signatory.yaml
#      - ./secret.json:/etc/secret.json


networks:
  p2p:
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
