import { PeerId } from '@libp2p/interface-peer-id';
import BigNumber from 'bignumber.js';
import type { ReportGenLeaderService } from './reportgen.leader.service.js';

export interface IReportGenEvents {
  observe: (from: PeerId, observeMessage: IObserveMessage) => Promise<void>;
  observeReq: (from: PeerId, round: IObserveReqMessage) => Promise<void>;
  reportReq: (from: PeerId, reportReqMessage: IReportReqMessage) => Promise<void>;
  report: (from: PeerId, reportMessage: IReportMessage) => Promise<void>;
  final: (from: PeerId, finalMessage: IFinalMessage) => Promise<void>;
  finalEcho: (from: PeerId, finalEchoMessage: IFinalEchoMessage) => Promise<void>;
}

export interface IObserveMessage {
  aggregatorAddress: string;
  epoch: number;
  round: number;
  observation: BigNumber;
  signature: Uint8Array;
}

export interface IFinalMessage {
  aggregatorAddress: string;
  attestedReport: IAttestedReport;
}

export interface IFinalEchoMessage {
  aggregatorAddress: string;
  attestedReport: IAttestedReport;
}

export interface IObserveReqMessage {
  aggregatorAddress: string;
  round: number;
}

export interface IReportMessage {
  aggregatorAddress: string;
  compressedReport: ICompressedReport;
  signature: ISignature;
}

export interface IReportReqMessage {
  aggregatorAddress: string;
  report: IReport;
}

/**
 * Observation.
 *
 * Once signed it becomes a {@link ISignedObservation}.
 */
export interface IObservation {
  // Oracle peer id
  oracle: string;

  // Observation
  price: BigNumber;
}

/**
 * Signed Observation.
 * This is generated by signing an {@link IObservation}
 * This is an observation from an oracle with its signature.
 * This is signed by the peer id private key
 */
export interface ISignedObservation {
  // Signing oracle Peer id
  oracle: string;

  // Observation
  price: BigNumber;

  // Signed using peer private key
  signature: Uint8Array;
}

/**
 * Report signature.
 * This is signature of the whole report.
 * This is signed by the Tezos private key
 * Do not mix with {@link ISignedObservation}, which is a signed observation.
 */
export interface ISignature {
  // Signing oracle public key hash
  oracle: string;

  // Signed using tezos private key
  signature: string;
}

/**
 * Report
 *
 * Contains signed observation from multiple oracles
 */
export interface IReport {
  epoch: number;
  round: number;
  observations: ISignedObservation[];
}

/**
 * Compressed report.
 *
 * Same as a {@link IReport} but without observation signatures.
 * Observation signatures are not needed after verifying them.
 * Compressed report are meant to be signed and become an {@link IAttestedReport}
 */
export interface ICompressedReport {
  epoch: number;
  round: number;
  observations: IObservation[];
}

/**
 * Attested report.
 *
 * Same as a {@link IReport}, but without observation signature and with report signatures.
 * This is generated from {@link IAttestedReport}
 */
export interface IAttestedReport {
  epoch: number;
  round: number;
  observations: IObservation[];
  signatures: ISignature[];
}

export enum Phase {
  Observe,
  Grace,
  Report,
  Final
}

/**
 * Internal state of {@link ReportGenLeaderService}.
 *
 * Used for testing
 */
export interface IReportGenLeaderState {
  epoch: number;
  leader: string;
  round: number;
  observe: Map<
    string,
    {
      observation: BigNumber;
      signature: Uint8Array;
    }
  >;
  reports: Map<
    string,
    {
      report: ICompressedReport;
      signature: ISignature;
    }
  >;
  phase: Phase | null;
}
