name: Pre-Release
on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit test (Node ${{ matrix.node }}, ${{ matrix.architecture }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]
        architecture: ["x64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}
          cache: "yarn"

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - run: npx nx workspace-lint

      - run: npx nx format:check

      - run: npx nx affected --target=lint --parallel=3

      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage

      - run: npx nx affected --target=build --parallel=3
